name = "AnalisisModalEstructural"
uuid = "ab970933-2879-4166-8151-057939dffbe5"
authors = ["Bruno Bazzano <bbazzzano@fing.edu.uy>",
	   "Marcelo Forets <mforets@gmail.com>",
           "Jorge Perez Zerpa <jorgepz@fing.edu.uy>"]
version = "0.1.0"
